### PR TITLE
Upgrade to can-symlink 1.0.0

### PR DESCRIPTION
**Pull request by john-kurkowski**
Fixes race condition in multiprocess environment (raytiley/can-symlink#3).

### CODE REVIEW

**Comment by stefanpenner** [comment]
LGTM thanks :)

**Comment by john-kurkowski** [comment]
Not sure what happened with the AppVeyor build. The Node.js 0.10 target timed out?

**Comment by stefanpenner** [comment]
seemed unrelated, triggering node 0.10 rebuild...

**Comment by joliss** [comment]
Thanks! Released in 1.1.1.

**Pull request merged**
