### PR TITLE
Using change tracking

### PR DESCRIPTION
**Pull request by arthirm**

### CODE REVIEW

**Comment by joliss** [comment]
Thanks. The `this.in` API is nowhere near landing in Broccoli core, so I don't think it's terribly useful to look at the changes from broccoli-merge-tree's end yet.

**Comment by stefanpenner** [comment]
@joliss this is to a WIP branch, not master.

**Comment by joliss** [comment]
Oh, I wasn't aware somebody was using this. I've reopened.

**Comment by joliss** [comment]
I think this is now redundant thanks to https://github.com/broccolijs/node-merge-trees/commit/5af53b922dffbb6a16dc7fc68df2b38d3c2f9a9c.

**Pull request closed without merging**
