### PR TITLE
Make things faster

### PR DESCRIPTION
**Pull request by stefanpenner**
a8c25f3e-6b72-11e5-8d21-4160f3feb531

- [x] release + use latest fs-tree-diff
- [x] fix canSymlink check
- [x] confirm in some more real world apps.
- [x] test real world apps on windows

----

bellow is Ember.js broccoli rebuild, it is an example of a project that has excessive number of merge-trees. It really should be refactored to avoid this many, but for now it serves a good stress test for merges.

ember-rebuild

before:

```
➜  ember.js git:(master) ✗ file changed debug.js

Build successful - 788ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
BroccoliMergeTrees                            | 96ms
BroccoliMergeTrees                            | 69ms
BroccoliMergeTrees                            | 63ms
Babel                                         | 53ms
BroccoliMergeTrees                            | 49ms
SimpleReplace                                 | 42ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
BroccoliMergeTrees (34)                       | 486ms (14 ms)
Babel (19)                                    | 82ms (4 ms)
SimpleReplace (5)                             | 67ms (13 ms)
ConcatWithMaps (8)                            | 47ms (5 ms)
Funnel (51)                                   | 41ms (0 ms)
```

after

```
➜  ember.js git:(master) ✗ file changed debug.js

Build successful - 342ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
Babel                                         | 37ms
SimpleReplace                                 | 30ms
ConcatWithMaps                                | 27ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
BroccoliMergeTrees (34)                       | 78ms (2 ms)
Babel (19)                                    | 57ms (3 ms)
SimpleReplace (5)                             | 53ms (10 ms)
ConcatWithMaps (8)                            | 42ms (5 ms)
Funnel (51)                                   | 35ms (0 ms)
JSHinter (30)                                 | 29ms (0 ms)
 (30)                                         | 23ms (0 ms)

```

@hjdivad & @stefanpenner 

----

This also got one of our large apps (200kloc of app.js code + 10k less + addons + vendor) from 800/900ms to 450ms rebuilds

### CODE REVIEW

**Comment by stefanpenner** [comment]
@joliss i have separated the method extraction and improvements into two seperate commits

* https://github.com/broccolijs/broccoli-merge-trees/commit/0a8e39985b2741e37b1d1e55797ad2a8dd9f1382
* https://github.com/broccolijs/broccoli-merge-trees/commit/02fb38dcf2cf5273eeba5d2c982ca4880d575d76

**Comment by jonnii** [comment]
excited to see how this affects our rebuild times.

**Comment by joliss** [comment]
Done with reviewing. All my comments are on 02fb38dcf2cf5273eeba5d2c982ca4880d575d76. (GitHub, y u no display context when I comment on individual commits.)

**Comment by stefanpenner** [comment]
@joliss it is pretty generic. But so far each use-case has had different implementations, this is by far the most general. A future refactoring can look into this, but I think a different approach will yield a better refactoring.

I'm slowly starting on the next approach, I expect something by q1 or so.

**Comment by hjdivad** [comment]
> Done with reviewing. All my comments are on 02fb38d. (GitHub, y u no display context when I comment on individual commits.)

@joliss this is one of my pet peeves with the PR code review system too :crying_cat_face:

**Comment by jonnii** [comment]
btw, tried this on windows and it does make a material difference. :+1:

**Comment by stefanpenner** [comment]
@jonnii can you share #'s ?

**Comment by jonnii** [comment]
I will get those for you Monday.

**Comment by stefanpenner** [comment]
> I will get those for you Monday.

sg :)

**Comment by jonnii** [comment]
@stefanpenner sorry for delay:

```
before
cold 17406
inc  1807
warm 4303

after
cold 16914
inc  1034
warm 4421
```

**Comment by stefanpenner** [comment]
@jonnii awesome :)

**Comment by jonnii** [comment]
@stefanpenner yeah, it's actually very noticeable.You'd think 800ms wouldn't be a big deal, but turns out it is.

**Comment by stefanpenner** [comment]
@joliss what needs to be done to merge this.

**Comment by joliss** [comment]
Merged and released in 1.1.0. Thanks @stefanpenner and @hjdivad!

If you still wanted to add a test for the `'change'` command (see [my comment](https://github.com/broccolijs/broccoli-merge-trees/pull/36#issuecomment-163268806)), do send a PR!

**Comment by stefanpenner** [comment]
@joliss thanks, I will follow up with a test with you suggestions this weekend.

I'm going to be taking the next week or so, to get the ember-cli 2.0 release out, then I'll circle back and work on another set of broccoli improvements. (Largely to improve the ergonomics of writing performant plugins, but it should also improve the performance again nicely). Thanks for iterating with us.

**Pull request merged**
