### PR TITLE
single input, doesn’t require merge.

### PR DESCRIPTION
**Pull request by stefanpenner**
on very large programmatically built trees, this helps quite a-bit.

### CODE REVIEW

**Comment by rwjblue** [comment]
I think we short cuircuit the work in build when we only have one input tree , but this prevents even a bit more work than that (no temp creation, less extra layers in viz graph, etc).

:+1:

**Comment by stefanpenner** [comment]
this confuses internal annotations.

**Comment by joliss** [comment]
I think the confusingness might be a bit of a problem. We're losing the annotation, and since we're encouraging `new`, it's also a bit unexpected to get an object that *isn't* an instance of `MergeTrees`.

I'm unsure how to do it better though.

**Comment by joliss** [comment]
I would suggest we close this, unless you want to keep it open.

**Pull request closed without merging**
