### PR TITLE
Improve error message

### PR DESCRIPTION
**Pull request by stefanpenner**
```
TypeError: broccoli-merge-trees: requires inputNodes to be all trees, but got: [,generators,[Babel],[Creator: Creator bootstrap],[BroccoliMergeTrees]]
```

### CODE REVIEW

**Comment by joliss** [comment]
See https://github.com/broccolijs/broccoli-merge-trees/issues/24#issuecomment-147372815 - I think the new builder will be able to do everything this code does.

**Comment by stefanpenner** [comment]
yup, but this will provide useful feedback today (if we merge and release)

tests inbound

**Comment by stefanpenner** [comment]
Oh, I suspect the builder will also provide feedback after the brocfile has already been invoked. This provides it immediately. 

Unless i don't understand what the new builder does.

**Comment by rwjblue** [comment]
Throwing in the constructor like this when we can (like when inputs are invalid) actually provides much better stack traces (since it includes actual the line that the user entered in `Brocfile.js` or `ember-cli-build.js` instead of some random promise-land stack).

**Comment by stefanpenner** [comment]
moving this to broccoli-plugin so all subclasses benefit.

**Comment by joliss** [comment]
@rwjblue FYI, with the new builder we'll also get those nice stacks into `Brocfile.js` in the error message, because plugin constructors capture their `instantiationStack`.

**Comment by rwjblue** [comment]
@joliss - Yep, I recall discussing that a while back. It will be awesome when we can move the Broccoli forward a few more inches and can take advantage of that.  In the meantime, we should help folks from this foot-rocket-launcher today :stuck_out_tongue_closed_eyes:

**Comment by stefanpenner** [comment]
superseded by https://github.com/broccolijs/broccoli-plugin/pull/7

**Pull request closed without merging**
